-- Active: 1753445442717@@127.0.0.1@3306@pdo_example

CREATE DATABASE IF NOT EXISTS pdo_example
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE pdo_example;

DROP TABLE IF EXISTS utilisateurs;

CREATE TABLE utilisateurs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
